name: Health check

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Health check
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-late-waterfall-1284.fly.dev/health
          max-attempts: 3
          retry-delay: 5s